In [24]:
!pip install pandas numpy scikit-learn scipy category_encoders

Requirement already satisfied: pandas in c:\users\patel prins\appdata\local\programs\python\python311\lib\site-packages (3.0.3)
Requirement already satisfied: numpy in c:\users\patel prins\appdata\local\programs\python\python311\lib\site-packages (2.4.5)
Requirement already satisfied: scikit-learn in c:\users\patel prins\appdata\local\programs\python\python311\lib\site-packages (1.8.0)
Requirement already satisfied: scipy in c:\users\patel prins\appdata\local\programs\python\python311\lib\site-packages (1.17.1)
Requirement already satisfied: category_encoders in c:\users\patel prins\appdata\local\programs\python\python311\lib\site-packages (2.9.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\patel prins\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\patel prins\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: joblib>=1.3.0 in c:\users\patel prins\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\patel prins\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: patsy>=0.5.1 in c:\users\patel prins\appdata\local\programs\python\python311\lib\site-packages (from category_encoders) (1.0.2)
Requirement already satisfied: statsmodels>=0.9.0 in c:\users\patel prins\appdata\local\programs\python\python311\lib\site-packages (from category_encoders) (0.14.6)
Requirement already satisfied: six>=1.5 in c:\users\patel prins\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: packaging>=21.3 in c:\users\patel prins\appdata\local\programs\python\python311\lib\site-packages (from statsmodels>=0.9.0->category_encoders) (26.2)

[notice] A new release of pip available: 22.3 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [25]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.impute import KNNImputer
from sklearn.preprocessing import OneHotEncoder
from scipy import stats
import category_encoders as ce

In [26]:
df = pd.read_csv('dataset.csv')

print("Dataset Loaded Successfully")
df.head()

Dataset Loaded Successfully

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [27]:
print("Missing Values in Dataset:\n")

print(df.isnull().sum())

Missing Values in Dataset:

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [28]:
if 'Age' in df.columns:
    
    mean_imputer = SimpleImputer(strategy='mean')
    
    df['Age'] = mean_imputer.fit_transform(df[['Age']])
    
    print("Mean Imputation Applied on Age Column")

Mean Imputation Applied on Age Column

In [29]:
mode_imputer = SimpleImputer(strategy='most_frequent')

df['Embarked'] = mode_imputer.fit_transform(df[['Embarked']]).ravel()

print("Missing values in Embarked filled using Mode")

Missing values in Embarked filled using Mode

In [30]:
median_imputer = SimpleImputer(strategy='median')

df['Fare'] = median_imputer.fit_transform(df[['Fare']])

print("Missing values in Fare filled using Median")

Missing values in Fare filled using Median

In [31]:
# Select numerical columns from Titanic dataset

numeric_cols = [
    'Age',
    'Fare',
    'SibSp',
    'Parch'
]

# Create KNN Imputer

knn_imputer = KNNImputer(
    n_neighbors=3
)

# Apply KNN Imputation

df[numeric_cols] = knn_imputer.fit_transform(
    df[numeric_cols]
)

print("KNN Imputation Applied Successfully")

df[numeric_cols].head()

KNN Imputation Applied Successfully

    Age     Fare  SibSp  Parch
0  22.0   7.2500    1.0    0.0
1  38.0  71.2833    1.0    0.0
2  26.0   7.9250    0.0    0.0
3  35.0  53.1000    1.0    0.0
4  35.0   8.0500    0.0    0.0

In [32]:
df['Cabin'] = df['Cabin'].fillna('Unknown')

print("Cabin missing values replaced with 'Unknown'")

Cabin missing values replaced with 'Unknown'

In [33]:
print(df.isnull().sum())

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [34]:
z_scores = np.abs(stats.zscore(df['Fare']))

df = df[z_scores < 3]

print("Outliers Removed from Fare Column")

Outliers Removed from Fare Column

In [35]:
Q1 = df['Fare'].quantile(0.25)

Q3 = df['Fare'].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

df = df[
    (df['Fare'] >= lower_bound) &
    (df['Fare'] <= upper_bound)
]

print("Outliers Removed Using IQR")

Outliers Removed Using IQR

In [36]:
print(df.memory_usage(deep=True))

Index           6176
PassengerId     6176
Survived        6176
Pclass          6176
Name           64432
Sex            47576
Age             6176
SibSp           6176
Parch           6176
Ticket         49221
Fare            6176
Cabin          48969
Embarked       44776
dtype: int64

In [37]:
# Integer columns

for col in df.select_dtypes(include=['int64']).columns:
    
    df[col] = pd.to_numeric(df[col], downcast='integer')


# Float columns

for col in df.select_dtypes(include=['float64']).columns:
    
    df[col] = pd.to_numeric(df[col], downcast='float')


# Object columns to category

for col in df.select_dtypes(include=['object']).columns:
    
    df[col] = df[col].astype('category')

print("Memory Optimization Completed")

Memory Optimization Completed

C:\Users\PATEL PRINS\AppData\Local\Temp\ipykernel_28660\108611937.py:17: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include=['object']).columns:

In [38]:
print(df.memory_usage(deep=True))

Index           6176
PassengerId     1544
Survived         772
Pclass           772
Name           65976
Sex              896
Age             3088
SibSp           3088
Parch           3088
Ticket         41766
Fare            3088
Cabin           6012
Embarked         946
dtype: int64

In [39]:
df_encoded = pd.get_dummies(
    df,
    columns=['Sex', 'Embarked', 'Cabin']
)

print("One-Hot Encoding Applied")

df_encoded.head()

One-Hot Encoding Applied

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Sex_female,...,Cabin_F E69,Cabin_F G63,Cabin_F G73,Cabin_F2,Cabin_F33,Cabin_F38,Cabin_F4,Cabin_G6,Cabin_T,Cabin_Unknown
0,1,0,3,"Braund, Mr. Owen Harris",22.000000,1.0,0.0,A/5 21171,7.250000,False,...,False,False,False,False,False,False,False,False,False,True
2,3,1,3,"Heikkinen, Miss. Laina",26.000000,0.0,0.0,STON/O2. 3101282,7.925000,True,...,False,False,False,False,False,False,False,False,False,True
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.000000,1.0,0.0,113803,53.099998,True,...,False,False,False,False,False,False,False,False,False,False
4,5,0,3,"Allen, Mr. William Henry",35.000000,0.0,0.0,373450,8.050000,False,...,False,False,False,False,False,False,False,False,False,True
5,6,0,3,"Moran, Mr. James",29.699118,0.0,0.0,330877,8.458300,False,...,False,False,False,False,False,False,False,False,False,True

In [40]:
encoder = ce.TargetEncoder(cols=['Pclass'])

df['Pclass'] = encoder.fit_transform(
    df['Pclass'],
    df['Survived']
)

print("Target Encoding Applied on Pclass")

df.head()

Target Encoding Applied on Pclass

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,0.245868,"Braund, Mr. Owen Harris",male,22.000000,1.0,0.0,A/5 21171,7.250000,Unknown,S
2,3,1,0.245868,"Heikkinen, Miss. Laina",female,26.000000,0.0,0.0,STON/O2. 3101282,7.925000,Unknown,S
3,4,1,0.504486,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1.0,0.0,113803,53.099998,C123,S
4,5,0,0.245868,"Allen, Mr. William Henry",male,35.000000,0.0,0.0,373450,8.050000,Unknown,S
5,6,0,0.245868,"Moran, Mr. James",male,29.699118,0.0,0.0,330877,8.458300,Unknown,Q

In [41]:
df_encoded.to_csv(
    'processed_titanic_dataset.csv',
    index=False
)

print("Processed Dataset Saved Successfully")

Processed Dataset Saved Successfully

In [42]:
df_encoded.head()

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Sex_female,...,Cabin_F E69,Cabin_F G63,Cabin_F G73,Cabin_F2,Cabin_F33,Cabin_F38,Cabin_F4,Cabin_G6,Cabin_T,Cabin_Unknown
0,1,0,3,"Braund, Mr. Owen Harris",22.000000,1.0,0.0,A/5 21171,7.250000,False,...,False,False,False,False,False,False,False,False,False,True
2,3,1,3,"Heikkinen, Miss. Laina",26.000000,0.0,0.0,STON/O2. 3101282,7.925000,True,...,False,False,False,False,False,False,False,False,False,True
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.000000,1.0,0.0,113803,53.099998,True,...,False,False,False,False,False,False,False,False,False,False
4,5,0,3,"Allen, Mr. William Henry",35.000000,0.0,0.0,373450,8.050000,False,...,False,False,False,False,False,False,False,False,False,True
5,6,0,3,"Moran, Mr. James",29.699118,0.0,0.0,330877,8.458300,False,...,False,False,False,False,False,False,False,False,False,True

In [43]:
new_df = pd.read_csv(
    'processed_titanic_dataset.csv'
)

new_df.head()

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Sex_female,...,Cabin_F E69,Cabin_F G63,Cabin_F G73,Cabin_F2,Cabin_F33,Cabin_F38,Cabin_F4,Cabin_G6,Cabin_T,Cabin_Unknown
0,1,0,3,"Braund, Mr. Owen Harris",22.000000,1.0,0.0,A/5 21171,7.2500,False,...,False,False,False,False,False,False,False,False,False,True
1,3,1,3,"Heikkinen, Miss. Laina",26.000000,0.0,0.0,STON/O2. 3101282,7.9250,True,...,False,False,False,False,False,False,False,False,False,True
2,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.000000,1.0,0.0,113803,53.1000,True,...,False,False,False,False,False,False,False,False,False,False
3,5,0,3,"Allen, Mr. William Henry",35.000000,0.0,0.0,373450,8.0500,False,...,False,False,False,False,False,False,False,False,False,True
4,6,0,3,"Moran, Mr. James",29.699118,0.0,0.0,330877,8.4583,False,...,False,False,False,False,False,False,False,False,False,True

In [44]:
import pandas as pd

output_df = pd.read_csv(
    'processed_titanic_dataset.csv'
)

print("Output Dataset Loaded Successfully")

Output Dataset Loaded Successfully

In [45]:
pd.set_option('display.max_rows', None)

pd.set_option('display.max_columns', None)

display(output_df)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              3         1       3
2              4         1       1
3              5         0       3
4              6         0       3
5              7         0       1
6              8         0       3
7              9         1       3
8             10         1       2
9             11         1       3
10            12         1       1
11            13         0       3
12            14         0       3
13            15         0       3
14            16         1       2
15            17         0       3
16            18         1       2
17            19         0       3
18            20         1       3
19            21         0       2
20            22         1       2
21            23         1       3
22            24         1       1
23            25         0       3
24            26         1       3
25            27         0       3
26            29         1       3
27            30         0       3
28            31         0       1
29            33         1       3
30            34         0       2
31            36         0       1
32            37         1       3
33            38         0       3
34            39         0       3
35            40         1       3
36            41         0       3
37            42         0       2
38            43         0       3
39            44         1       2
40            45         1       3
41            46         0       3
42            47         0       3
43            48         1       3
44            49         0       3
45            50         0       3
46            51         0       3
47            52         0       3
48            54         1       2
49            55         0       1
50            56         1       1
51            57         1       2
52            58         0       3
53            59         1       2
54            60         0       3
55            61         0       3
56            64         0       3
57            65         0       1
58            66         1       3
59            67         1       2
60            68         0       3
61            69         1       3
62            70         0       3
63            71         0       2
64            72         0       3
65            74         0       3
66            75         1       3
67            76         0       3
68            77         0       3
69            78         0       3
70            79         1       2
71            80         1       3
72            81         0       3
73            82         1       3
74            83         1       3
75            84         0       1
76            85         1       2
77            86         1       3
78            87         0       3
79            88         0       3
80            90         0       3
81            91         0       3
82            92         0       3
83            93         0       1
84            94         0       3
85            95         0       3
86            96         0       3
87            97         0       1
88            99         1       2
89           100         0       2
90           101         0       3
91           102         0       3
92           104         0       3
93           105         0       3
94           106         0       3
95           107         1       3
96           108         1       3
97           109         0       3
98           110         1       3
99           111         0       1
100          112         0       3
101          113         0       3
102          114         0       3
103          115         0       3
104          116         0       3
105          117         0       3
106          118         0       2
107          120         0       3
108          122         0       3
109          123         0       2
110          124         1       2
111          126         1       3
112          127         0       3
113          128         1       3
114          129         1       3
115          130         0       3
116          131         0       3
117          132         0       3
118          133         0       3
119          134         1       2
120          135         0       2
121          136         0       2
122          137         1       1
123          138         0       1
124          139         0       3
125          141         0       3
126          142         1       3
127          143         1       3
128          144         0       3
129          145         0       2
130          146         0       2
131          147         1       3
132          148         0       3
133          149         0       2
134          150         0       2
135          151         0       2
136          153         0       3
137          154         0       3
138          155         0       3
139          156         0       1
140          157         1       3
141          158         0       3
142          159         0       3
143          161         0       3
144          162         1       2
145          163         0       3
146          164         0       3
147          165         0       3
148          166         1       3
149          167         1       1
150          168         0       3
151          169         0       1
152          170         0       3
153          171         0       1
154          172         0       3
155          173         1       3
156          174         0       3
157          175         0       1
158          176         0       3
159          177         0       3
160          178         0       1
161          179         0       2
162          180         0       3
163          182         0       2
164          183         0       3
165          184         1       2
166          185         1       3
167          186         0       1
168          187         1       3
169          188         1       1
170          189         0       3
171          190         0       3
172          191         1       2
173          192         0       2
174          193         1       3
175          194         1       2
176          195         1       1
177          197         0       3
178          198         0       3
179          199         1       3
180          200         0       2
181          201         0       3
182          203         0       3
183          204         0       3
184          205         1       3
185          206         0       3
186          207         0       3
187          208         1       3
188          209         1       3
189          210         1       1
190          211         0       3
191          212         1       2
192          213         0       3
193          214         0       2
194          215         0       3
195          217         1       3
196          218         0       2
197          220         0       2
198          221         1       3
199          222         0       2
200          223         0       3
201          224         0       3
202          226         0       3
203          227         1       2
204          228         0       3
205          229         0       2
206          230         0       3
207          232         0       3
208          233         0       2
209          234         1       3
210          235         0       2
211          236         0       3
212          237         0       2
213          238         1       2
214          239         0       2
215          240         0       2
216          241         0       3
217          242         1       3
218          243         0       2
219          244         0       3
220          245         0       3
221          247         0       3
222          248         1       2
223          249         1       1
224          250         0       2
225          251         0       3
226          252         0       3
227          253         0       1
228          254         0       3
229          255         0       3
230          256         1       3
231          260         1       2
232          261         0       3
233          262         1       3
234          264         0       1
235          265         0       3
236          266         0       2
237          267         0       3
238          268         1       3
239          271         0       1
240          272         1       3
241          273         1       2
242          274         0       1
243          275         1       3
244          277         0       3
245          278         0       2
246          279         0       3
247          280         1       3
248          281         0       3
249          282         0       3
250          283         0       3
251          284         1       3
252          285         0       1
253          286         0       3
254          287         1       3
255          288         0       3
256          289         1       2
257          290         1       3
258          293         0       2
259          294         0       3
260          295         0       3
261          296         0       1
262          297         0       3
263          299         1       1
264          301         1       3
265          302         1       3
266          303         0       3
267          304         1       2
268          305         0       3
269          309         0       2
270          310         1       1
271          313         0       2
272          314         0       3
273          315         0       2
274          316         1       3
275          317         1       2
276          318         0       2
277          321         0       3
278          322         0       3
279          323         1       2
280          324         1       2
281          327         0       3
282          328         1       2
283          329         1       3
284          330         1       1
285          331         1       3
286          332         0       1
287          334         0       3
288          336         0       3
289          339         1       3
290          340         0       1
291          341         1       2
292          343         0       2
293          344         0       2
294          345         0       2
295          346         1       2
296          347         1       2
297          348         1       3
298          349         1       3
299          350         0       3
300          351         0       3
301          352         0       1
302          353         0       3
303          354         0       3
304          355         0       3
305          356         0       3
306          357         1       1
307          358         0       2
308          359         1       3
309          360         1       3
310          361         0       3
311          362         0       2
312          363         0       3
313          364         0       3
314          365         0       3
315          366         0       3
316          368         1       3
317          369         1       3
318          371         1       1
319          372         0       3
320          373         0       3
321          375         0       3
322          377         1       3
323          379         0       3
324          380         0       3
325          382         1       3
326          383         0       3
327          384         1       1
328          385         0       3
329          387         0       3
330          388         1       2
331          389         0       3
332          390         1       2
333          392         1       3
334          393         0       3
335          395         1       3
336          396         0       3
337          397         0       3
338          398         0       2
339          399         0       2
340          400         1       2
341          401         1       3
342          402         0       3
343          403         0       3
344          404         0       3
345          405         0       3
346          406         0       2
347          407         0       3
348          408         1       2
349          409         0       3
350          410         0       3
351          411         0       3
352          412         0       3
353          414         0       2
354          415         1       3
355          416         0       3
356          417         1       2
357          418         1       2
358          419         0       2
359          420         0       3
360          421         0       3
361          422         0       3
362          423         0       3
363          424         0       3
364          425         0       3
365          426         0       3
366          427         1       2
367          428         1       2
368          429         0       3
369          430         1       3
370          431         1       1
371          432         1       3
372          433         1       2
373          434         0       3
374          435         0       1
375          437         0       3
376          438         1       2
377          440         0       2
378          441         1       2
379          442         0       3
380          443         0       3
381          444         1       2
382          445         1       3
383          447         1       2
384          448         1       1
385          449         1       3
386          450         1       1
387          451         0       2
388          452         0       3
389          453         0       1
390          455         0       3
391          456         1       3
392          457         0       1
393          458         1       1
394          459         1       2
395          460         0       3
396          461         1       1
397          462         0       3
398          463         0       1
399          464         0       2
400          465         0       3
401          466         0       3
402          467         0       2
403          468         0       1
404          469         0       3
405          470         1       3
406          471         0       3
407          472         0       3
408          473         1       2
409          474         1       2
410          475         0       3
411          476         0       1
412          477         0       2
413          478         0       3
414          479         0       3
415          480         1       3
416          481         0       3
417          482         0       2
418          483         0       3
419          484         1       3
420          486         0       3
421          488         0       1
422          489         0       3
423          490         1       3
424          491         0       3
425          492         0       3
426          493         0       1
427          494         0       1
428          495         0       3
429          496         0       3
430          498         0       3
431          500         0       3
432          501         0       3
433          502         0       3
434          503         0       3
435          504         0       3
436          507         1       2
437          508         1       1
438          509         0       3
439          510         1       3
440          511         1       3
441          512         0       3
442          513         1       1
443          514         1       1
444          515         0       3
445          516         0       1
446          517         1       2
447          518         0       3
448          519         1       2
449          520         0       3
450          522         0       3
451          523         0       3
452          524         1       1
453          525         0       3
454          526         0       3
455          527         1       2
456          529         0       3
457          530         0       2
458          531         1       2
459          532         0       3
460          533         0       3
461          534         1       3
462          535         0       3
463          536         1       2
464          537         0       1
465          539         0       3
466          540         1       1
467          542         0       3
468          543         0       3
469          544         1       2
470          546         0       1
471          547         1       2
472          548         1       2
473          549         0       3
474          550         1       2
475          552         0       2
476          553         0       3
477          554         1       3
478          555         1       3
479          556         0       1
480          557         1       1
481          560         1       3
482          561         0       3
483          562         0       3
484          563         0       2
485          564         0       3
486          565         0       3
487          566         0       3
488          567         0       3
489          568         0       3
490          569         0       3
491          570         1       3
492          571         1       2
493          572         1       1
494          573         1       1
495          574         1       3
496          575         0       3
497          576         0       3
498          577         1       2
499          578         1       1
500          579         0       3
501          580         1       3
502          581         1       2
503          583         0       2
504          584         0       1
505          585         0       3
506          587         0       2
507          589         0       3
508          590         0       3
509          591         0       3
510          593         0       3
511          594         0       3
512          595         0       2
513          596         0       3
514          597         1       2
515          598         0       3
516          599         0       3
517          600         1       1
518          601         1       2
519          602         0       3
520          603         0       1
521          604         0       3
522          605         1       1
523          606         0       3
524          607         0       3
525          608         1       1
526          609         1       2
527          611         0       3
528          612         0       3
529          613         1       3
530          614         0       3
531          615         0       3
532          617         0       3
533          618         0       3
534          619         1       2
535          620         0       2
536          621         0       3
537          622         1       1
538          623         1       3
539          624         0       3
540          625         0       3
541          626         0       1
542          627         0       2
543          629         0       3
544          630         0       3
545          631         1       1
546          632         0       3
547          633         1       1
548          634         0       1
549          635         0       3
550          636         1       2
551          637         0       3
552          638         0       2
553          639         0       3
554          640         0       3
555          641         0       3
556          643         0       3
557          644         1       3
558          645         1       3
559          647         0       3
560          648         1       1
561          649         0       3
562          650         1       3
563          651         0       3
564          652         1       2
565          653         0       3
566          654         1       3
567          655         0       3
568          657         0       3
569          658         0       3